import { COI } from 'src/types/coi'

export const MOCK_COIS: COI[] = [
  {
    id: 1,
    property: 'Maplewood Shopping Center',
    tenantName: 'Johnson & Sons',
    tenantEmail: 'johnson@example.com',
    unit: '101',
    coiName: 'Tenant_CedarHeights_COI_2026',
    expiryDate: '2026-11-17',
    status: 'Active',
    reminderStatus: 'Not Sent',
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 2,
    property: 'Oak Tree Tower',
    tenantName: 'Smith Enterprises',
    tenantEmail: 'smith@example.com',
    unit: 'Suite 300',
    coiName: 'GlobalMart_Insurance_COI_2025',
    expiryDate: '2025-11-20',
    status: 'Expired',
    reminderStatus: 'Sent (30d)',
    createdAt: '2024-12-10T10:00:00Z',
  },
  {
    id: 3,
    property: 'Meadowbrook Plaza',
    tenantName: 'Global Solutions',
    tenantEmail: 'global@example.com',
    unit: 'B-12',
    coiName: 'UrbanOutfitters_COI_2027',
    expiryDate: '2027-11-19',
    status: 'Rejected',
    reminderStatus: 'N/A',
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 4,
    property: 'Pine Hill Shopping Center',
    tenantName: 'Patel Industries',
    tenantEmail: 'patel@example.com',
    unit: '402',
    coiName: 'TechInnovators_COI_2028',
    expiryDate: '2028-11-23',
    status: 'Expiring Soon',
    reminderStatus: 'Not Sent',
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 5,
    property: 'Harbor Heights',
    tenantName: 'Smart Ventures',
    tenantEmail: 'smart@example.com',
    unit: 'Unit 5',
    coiName: 'SmartVentures_COI_2026',
    expiryDate: '2026-03-15',
    status: 'Expiring Soon',
    reminderStatus: 'Not Sent',
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 6,
    property: 'Cedar Driveways',
    tenantName: 'Wayne Enterprises',
    tenantEmail: 'wayne@example.com',
    unit: '200',
    coiName: 'WayneEnterprises_COI_2026',
    expiryDate: '2026-05-10',
    status: 'Active',
    reminderStatus: 'Sent (30d)',
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 7,
    property: 'Riverside Mall',
    tenantName: 'Modern Tech',
    tenantEmail: 'moderntech@example.com',
    unit: '150',
    coiName: 'ModernTech_COI_2027',
    expiryDate: '2027-06-20',
    status: 'Active',
    reminderStatus: 'Not Sent',
    createdAt: '2025-01-22T10:00:00Z',
  },
  {
    id: 8,
    property: 'Downtown Plaza',
    tenantName: 'City Ventures',
    tenantEmail: 'city@example.com',
    unit: '350',
    coiName: 'CityVentures_COI_2025',
    expiryDate: '2025-12-01',
    status: 'Not Processed',
    reminderStatus: 'Not Sent',
    createdAt: '2025-02-03T10:00:00Z',
  },
  {
    id: 9,
    property: 'Executive Tower',
    tenantName: 'Global Innovations',
    tenantEmail: 'global.innovations@example.com',
    unit: 'Suite 800',
    coiName: 'GlobalInnovations_COI_2026',
    expiryDate: '2026-09-30',
    status: 'Active',
    reminderStatus: 'Not Sent',
    createdAt: '2025-01-28T10:00:00Z',
  },
  {
    id: 10,
    property: 'Westside Commons',
    tenantName: 'Premier Services',
    tenantEmail: 'premier@example.com',
    unit: 'A-100',
    coiName: 'PremierServices_COI_2028',
    expiryDate: '2028-01-15',
    status: 'Active',
    reminderStatus: 'Not Sent',
    createdAt: '2025-02-02T10:00:00Z',
  },
  {
    id: 11,
    property: 'Market Street Complex',
    tenantName: 'Trade Associates',
    tenantEmail: 'trade@example.com',
    unit: '475',
    coiName: 'TradeAssociates_COI_2025',
    expiryDate: '2025-10-05',
    status: 'Expired',
    reminderStatus: 'Sent (60d)',
    createdAt: '2024-11-15T10:00:00Z',
  },
  {
    id: 12,
    property: 'Summit Office Park',
    tenantName: 'Digital Dynamics',
    tenantEmail: 'digital@example.com',
    unit: 'Building C',
    coiName: 'DigitalDynamics_COI_2026',
    expiryDate: '2026-07-22',
    status: 'Active',
    reminderStatus: 'Not Sent',
    createdAt: '2025-01-30T10:00:00Z',
  },
]
